In [2]:
principal,rate,time = 10000,24,3

In [3]:
principal

10000

In [40]:
customer_name ='radhika'
age=29
income=50000
credit_score =[690,700,729,359,800]
loan_amount =40000
loan_tenure =36
is_employe = True
has_he_defaulted = False

In [41]:
print('customer profile')
print('customer_name',customer_name)
print('age',age)
print('income',income)
print('loan_amount',loan_amount)
print('is_employe',is_employe)

customer profile
customer_name radhika
age 29
income 50000
loan_amount 40000
is_employe True

data types in python 
numeric - int,float
text -string
boolean 
collection - list, tuple, dict,set

sequence 
list = mutable,ordered collection
tuple = immutable,ordered collection
range = sequnce of numbers

In [42]:
customer_profile={'customer_name':customer_name,
'age':age,
'income':income,
'credit_score': credit_score,
'loan_amount':loan_amount,
'loan_tenure':loan_tenure,
'is_employe': is_employe,
'has_he_defaulted':has_he_defaulted }

In [7]:
customer_profile['age']

29

In [8]:
print(type(is_employe))

<class 'bool'>

there are some functions in list 
1.append-at end
2.insert-for precific index
3.extend-multiple item to add 
4.remove - particular item 
5.pop - remove through index
6.index() - finds the position of the item 
7.sort -ascending
8.clear - empty list

In [43]:
credit_score

[690, 700, 729, 359, 800]

In [10]:
credit_score.append(900)

In [11]:
credit_score.insert(2,710)

In [12]:
credit_score.extend([910,920,930])

In [13]:
credit_score.pop()

930

In [14]:
credit_score.pop(-1)

920

In [15]:
credit_score.remove(900)

In [16]:
credit_score.index(910)

6

In [17]:
credit_score.sort(reverse=True)

tuples inside list and vice versa

In [19]:
customers = [('cus1',790),('cus2',900),('cus3',800)]

In [20]:
for customer in customers:
    #print('id:',customer[0],'--score:',customer[1])
    print(customer)

('cus1', 790)
('cus2', 900)
('cus3', 800)

In [21]:
my_set = {1,2,3,4,5}
my_set.add(6)
my_set.remove(4)

In [22]:
print(my_set)

{1, 2, 3, 5, 6}

In [23]:
customer_profile.get('customer_name')

'radhika'

In [24]:
customer_profile.items()

dict_items([('customer_name', 'radhika'), ('age', 29), ('income', 50000), ('credit_score', []), ('loan_amount', 40000), ('loan_tenure', 36), ('is_employe', True), ('has_he_defaulted', False)])

In [25]:
customer_profile.keys()

dict_keys(['customer_name', 'age', 'income', 'credit_score', 'loan_amount', 'loan_tenure', 'is_employe', 'has_he_defaulted'])

In [26]:
customer_profile.values()

dict_values(['radhika', 29, 50000, [], 40000, 36, True, False])

In [27]:
for key,value in customer_profile.items():
    print(key,":",value)

customer_name : radhika
age : 29
income : 50000
credit_score : []
loan_amount : 40000
loan_tenure : 36
is_employe : True
has_he_defaulted : False

In [28]:
customer_profile.update({'age': 26})
customer_profile

{'customer_name': 'radhika',
 'age': 26,
 'income': 50000,
 'credit_score': [],
 'loan_amount': 40000,
 'loan_tenure': 36,
 'is_employe': True,
 'has_he_defaulted': False}

In [29]:
customer_profile.update({'city': 'bangalore'})
customer_profile

{'customer_name': 'radhika',
 'age': 26,
 'income': 50000,
 'credit_score': [],
 'loan_amount': 40000,
 'loan_tenure': 36,
 'is_employe': True,
 'has_he_defaulted': False,
 'city': 'bangalore'}

In [30]:
for key in customer_profile:
    if key == 'income':
        print('key exists')

key exists

In [31]:
required_keys = ['income','age','credit_score']

In [32]:
for key in customer_profile:
    if key in required_keys:
        print(key)

age
income
credit_score

In [33]:
nums = [12,1,2,23,45,2,45,12,34,54,45,66,88,99,9,1]
duplicate =[]
def duplicates():
    for num in nums:
        if nums.count(num)>1 and num not in duplicate:
            duplicate.append(num)
    return duplicate 
print(duplicates())

[12, 1, 2, 45]

In [34]:
nums = [12, 23, 13, 45, 65, 23, 12, 34, 56, 78, 35]

duplicate = []

def duplicates():
    for num in nums:
        if nums.count(num) > 1 and num not in duplicate:
            duplicate.append(num)

    return duplicate

print(duplicates())

[12, 23]

In [ ]:
df_month = (pd.to_datetime(df['month'],errors= 'coerce',format = '%Y-%m-%d')-pd.to_datetime('2026-09-01')).dt.days

In [44]:
print(customer_profile['age'])
print(customer_profile['customer_name'])
print(customer_profile['credit_score'])

29
radhika
[690, 700, 729, 359, 800]

In [46]:
customer_profile.update({'loan_purpose':'Home improvement'})

In [47]:
customer_profile

{'customer_name': 'radhika',
 'age': 29,
 'income': 50000,
 'credit_score': [690, 700, 729, 359, 800],
 'loan_amount': 40000,
 'loan_tenure': 36,
 'is_employe': True,
 'has_he_defaulted': False,
 'loan_purpose': 'Home improvement'}

In [51]:
for key,value in customer_profile.items():
    print(key, ":",value)

customer_name : radhika
age : 29
income : 50000
credit_score : [690, 700, 729, 359, 800]
loan_amount : 40000
loan_tenure : 36
is_employe : True
has_he_defaulted : False
loan_purpose : Home improvement

In [67]:
# nested dictiionary
customer = {
    "customer1":{'customer_name':'asha','age':29,'income':50000},
    "customer2":{'customer_name':'kasha','age':26,'income':90000},
    "customer3":{'customer_name':'dasha','age':39,'income':40000}
}
print(customer['customer1']['customer_name'])

asha

In [69]:
for i in customer:
    if customer[i]['income']>=90000:
        print(i,'approved')
    else:
        print(i,'rejected')

customer1 rejected
customer2 approved
customer3 rejected

In [74]:
dti = 0.96

if dti<0.36:
    print('low risk')
elif dti<0.45:
    print('medium risk')
elif dti<0.75:
    print('high risk')
else:
    print('very high risk')

very high risk

In [75]:
dti = 0.45 
income =50000

if dti <= 0.36 and income >= 40000 :
    print('low risk')
elif dti <=0.45 and income >= 50000 :
    print('medium risk')
elif dti > 0.45 and income >= 30000 :
    print ('high risk')
else:
    print('very high risk')

medium risk

In [76]:
credit =[ 700,500,600,400,500,399,900]

for i in credit:
    if i <= 400:
        print('high risk')
    elif i <= 600:
        print('medium risk')
    elif i <= 800:
        print('low risk')
    else:
        print('no risk')

low risk
medium risk
medium risk
high risk
medium risk
high risk
no risk

In [77]:
while dti > 0.36:
    print('high score:',{dti})
    dti-= 0.02

high score: {0.45}
high score: {0.43}
high score: {0.41}
high score: {0.38999999999999996}
high score: {0.36999999999999994}

In [81]:
applications =['alice ','bob','charlie']
index =0

while index < len(applications):
    print(f'the application under process{applications[index]}')
    if applications[index] == 'bob':
        print(f'the application has found {[applications[index]]}')
        break
    index += 1

the application under processalice
the application under processbob
the application has found ['bob']

In [97]:
namess ={
    'name1':{'id':1,'age':40,'credit_score':800},
    'name2' :{'id':2, 'age':45,'credit_score':700},
    'name3':{'id':3,'age':30,'credit_score':900}

}

In [98]:
for i in namess:
    if namess[i]['credit_score'] >= 800:
        continue

    print(f'application under review {namess[i]["credit_score"]}')

application under review 700

In [110]:
import numpy as np
import pandas as pd

In [113]:
df = pd.DataFrame({
    'name':['balaram','vishnu','nikhil','vinay'],
    'age':[25,27,26,31],
    'income':[30000,35000,50000,50000],
    'credit_score':[600,500,700,900]
})

In [114]:
df.head()

      name  age  income  credit_score
0  balaram   25   30000           600
1   vishnu   27   35000           500
2   nikhil   26   50000           700
3    vinay   31   50000           900

In [119]:
result = df.iloc[:3,:]
result

      name  age  income  credit_score
0  balaram   25   30000           600
1   vishnu   27   35000           500
2   nikhil   26   50000           700

In [125]:
Lresult =df.loc[0:1,:]

In [126]:
Lresult

      name  age  income  credit_score
0  balaram   25   30000           600
1   vishnu   27   35000           500

In [136]:
Lresult.loc[0:1,['name','age']]= [['ram',56],['vishnuraj',57]]

In [137]:
Lresult

        name  age  income  credit_score
0        ram   56   30000           600
1  vishnuraj   57   35000           500

In [123]:
result.iloc[0:2,0]=['chandru','sanketh']

In [124]:
result

      name  age  income  credit_score
0  chandru   25   30000           600
1  sanketh   27   35000           500
2   nikhil   26   50000           700

In [131]:
Lresult

     name  age  income  credit_score
0     ram   25   30000           600
1  jairam   27   35000           500

In [139]:
df.rename(columns={'age':'years'})

      name  years  income  credit_score
0  balaram     25   30000           600
1   vishnu     27   35000           500
2   nikhil     26   50000           700
3    vinay     31   50000           900

In [140]:
df

      name  age  income  credit_score
0  balaram   25   30000           600
1   vishnu   27   35000           500
2   nikhil   26   50000           700
3    vinay   31   50000           900